#!/usr/bin/env python3
"""Draw each major as a DAG of courses (each course = a block of its primary book), from curriculum.json.

    python3 scripts/major_dag.py            write topics/<major>/DAG.md for every major (or parked major) with a curriculum
    python3 scripts/major_dag.py --check    exit 1 if any DAG.md is out of date (run by check_all.sh)

Generated files: never edit DAG.md by hand.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def label(s, n=48):
    s = s.replace('"', "'")
    return s if len(s) <= n else s[: n - 1] + "…"


def book_short(ref):
    """'f9dc4d1d4c Casella & Berger, Statistical Inference, Ch. 1 (…)' -> 'Casella & Berger, Statistical Inference'."""
    parts = ref.split(" ", 1)
    is_id = len(parts) == 2 and len(parts[0]) == 10 and all(ch in "0123456789abcdef" for ch in parts[0])
    text = parts[1] if is_id else ref
    return ", ".join(text.split(", ")[:2]).split(" (")[0].split(":")[0]


def render(major, cur):
    courses = cur["courses"]
    lines = [f"# {major['name']}: the major as a DAG of books", "",
             "Generated by `scripts/major_dag.py` from `curriculum.json`; don't edit by hand. Each box is a course: a block of its",
             "primary book (\"book: …\" lines). Arrows point from a prerequisite to the course that needs it. Bold = active,",
             "grey = done, dashed = later or optional. Level II courses appear only once you enroll.", "",
             "```mermaid", "flowchart TB"]
    enrolled = set(major.get("enrolled_levels", ["I"]))
    shown = [c for c in courses if c.get("level", "I") in enrolled]
    ids = {c["id"] for c in shown}
    for c in shown:
        book = (c.get("books") or {}).get("primary") or c.get("source") or "book not chosen yet"
        text = f"{c['id']} {label(c['title'], 40)}<br/><small>book: {label(book_short(book), 44)}</small>"
        lines.append(f'  {c["id"]}["{text}"]')
    for c in shown:
        for r in c.get("requires", []):
            if r in ids:
                lines.append(f"  {r} --> {c['id']}")
    lines += ["  classDef done fill:#eee,color:#777,stroke:#bbb",
              "  classDef active stroke-width:3px",
              "  classDef later stroke-dasharray:5 4"]
    for c in shown:
        cls = {"done": "done", "active": "active"}.get(c["status"])
        if cls is None and (c["status"] == "later" or c.get("group", "core") != "core"):
            cls = "later"
        if cls:
            lines.append(f"  class {c['id']} {cls}")
    lines += ["```", ""]
    active = [c for c in shown if c["status"] == "active"]
    if active:
        lines += ["## Active courses: books by role", ""]
        for c in active:
            b = c.get("books") or {}
            lines.append(f"**{c['id']} {c['title']}**")
            lines.append(f"- primary: {b.get('primary', '—')}")
            for role in ("secondary", "tertiary", "skip"):
                for ref in b.get(role, []):
                    lines.append(f"- {role}: {ref}")
            lines.append("")
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv
    cfg = json.loads((ROOT / "programs.json").read_text(encoding="utf-8"))
    stale = []
    for m in cfg["majors"] + cfg.get("parked", []):
        if not m.get("curriculum"):
            continue
        cur = json.loads((ROOT / m["curriculum"]).read_text(encoding="utf-8"))
        out = ROOT / "topics" / m["slug"] / "DAG.md"
        text = render(m, cur)
        if check:
            if not out.exists() or out.read_text(encoding="utf-8") != text:
                stale.append(str(out.relative_to(ROOT)))
        else:
            out.write_text(text, encoding="utf-8")
            print("wrote", out.relative_to(ROOT))
    if check:
        if stale:
            print("stale (run python3 scripts/major_dag.py):", ", ".join(stale))
            sys.exit(1)
        print("dags: up to date")


if __name__ == "__main__":
    main()
